---
name: SonarCloud

"on":
  push:
    branches:
      - main
      - day05
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions: read-all

jobs:
  SonarCloud-Scanner:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # Shallow clones should be disabled for a better
          # relevancy of analysis
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # - name: install dependencies
      #   run: python -m pip install tox
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: run tox
      #   run: tox -e py
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
