---
name: SonarCloud

"on":
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions: read-all

jobs:
  SonarCloud-Scanner:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
        poetry-version:
          - 1.8.4
        os:
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4.2.2
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - run: poetry install
      - run: poetry run tox
      # - uses: sonarsource/sonarqube-scan-action@v4.1.0
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
